worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    client_max_body_size 15M;
    proxy_read_timeout 180s;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  _;
        
        # โฟลเดอร์หลักที่เก็บไฟล์ Frontend
        root html;

        # 1. ลิงก์ /auth/login -> ดึงไฟล์ auth.html มาแสดง
        location = /auth/login {
            try_files /auth.html =404;
        }

        # 2. ลิงก์ /generate -> ดึงไฟล์ index.html มาแสดง
        location = /generate {
            try_files /index.html =404;
        }

        # 3. เข้า IP ตรงๆ (หน้าแรกสุด) -> เด้งไปที่ /generate
	location = / {
            try_files /home.html =404;
        }

        # 4. อนุญาตให้เบราว์เซอร์โหลดไฟล์ css, js และรูปภาพได้
        location / {
            try_files $uri $uri/ =404;
        }

	# หน้า Admin Panel
        location /admin {
            try_files /admin.html =404;
        }

    # 6. ท่อส่งข้อมูลไปหา Backend ของเพื่อน (ห้ามเปลี่ยน /api/)
        location /api/ {
    		proxy_pass http://10.192.0.180:5000/;
   		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
	}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}